# Generated by Django 3.1.7 on 2021-03-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customuser_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('phnum', models.CharField(max_length=13)),
                ('p_fullname', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='charges',
            field=models.CharField(default='NULL', max_length=4),
        ),
    ]
