# Generated by Django 3.1.7 on 2021-03-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210316_0109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_table',
        ),
    ]
