# Generated by Django 3.1.7 on 2021-03-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('phnum', models.CharField(max_length=13)),
                ('fullname', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
