# Generated by Django 3.1.7 on 2021-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_customuser_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='service_provider',
            field=models.EmailField(default='NULL', max_length=254),
        ),
    ]
